# Generated by Django 3.2.4 on 2021-07-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20210721_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
